IBaiWebApp/Pages/CreateStore.cshtml.cs
using DataLayer;
using Domain_Layer.Classes;
using Domain_Layer.ClassManagers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Domain_Layer.Enums;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace IBaiWebApp.Pages
{
    [IgnoreAntiforgeryToken(Order = 1001)]
    public class CreateStoreModel : PageModel
    {
        public CreateStoreModel()
        {
            PageTitle = "New Store Form";
        }

        public string PageTitle { get; private set; }

        [BindProperty] public new Models.StoreModel NewStore { get; set; }
        StoreManager storeManager = new StoreManager(new StoreData());
        UserManager userManager = new UserManager(new UserData());
        
        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {
            // string? userName = HttpContext.Session.GetString("_UserName");
            // User selUser = userManager.GetUserByUserName(new User(0,userName));
            string userName = HttpContext.Session.GetString("_UserName");
            List<Categories> categories = new();
            ModelState.Remove("NewStore.Products");
            ModelState.Remove("NewStore.Owner");
            IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
             
            if (ModelState.IsValid)
            {
                User seluser = userManager.GetUserByUserName(new User(0, userName));
                Store newStore = new Store(0, seluser, NewStore.StoreName,NewStore.Description, NewStore.Categories);
                // to be fixed
                Store storeId = storeManager.GetStoreByName(new Store(NewStore.StoreName));
                storeManager.WriteStore(newStore);
                return RedirectToPage("/StorePage",storeId.StoreId);
            }
            return Page();
        }
    }
}

IBaiWebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace IBaiWebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

IBaiWebApp/Pages/Index.cshtml.cs
using IBaiWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Mail;
using Domain_Layer.Classes;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using DataLayer;
using Domain_Layer.ClassManagers;
using Domain_Layer.Classes;
namespace IBaiWebApp.Pages
{
    public class IndexModel : PageModel
    {
        ProductManager productManager = new ProductManager(new ProductData());
    
        [BindProperty] public new ProductModel selProduct { get; set; }
        public void OnGet()
        {
         
        }
        public IActionResult OnPostPassProduct(int productID)
        {
            return  RedirectToPage("/ProductPage?ID=" + productID);

        }
    }
}

IBaiWebApp/Pages/Login.cshtml.cs
using IBaiWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IBaiWebApp.Pages;

public class LoginModel : PageModel
{
    public const string SessionKeyUserName = "_UserName";
    public const string SessionKeyPassword = "_Password";
    public const string SessionKeyUserId = "_UserId";
    private readonly ILogger<IndexModel> _logger;
    public LoginModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
        PageTitle = "Login form";
    }
    public string PageTitle { get; private set; }
    [BindProperty] public new UserModel User { get; set; }
    public IActionResult OnGet()
    {
        if (HttpContext.Session.GetString(SessionKeyUserName) != null && HttpContext.Session.GetString(SessionKeyUserName) == User.UserName)
        {
            return new RedirectToPageResult("/Index");
        }
        return Page();
    }

    // interface that xecutes the result operation of the action method asynchronously
    // returns asynchronous methods
    // needed because 2 return paths are needed
    public IActionResult OnPost()
    {
        ModelState.Remove("User.Email");
        ModelState.Remove("User.TelephoneNumber");
        ModelState.Remove("User.Address");
        ModelState.Remove("User.FirstName");
        ModelState.Remove("User.LastName");
        var errors = ModelState.Values.SelectMany(v => v.Errors);
        if (ModelState.IsValid)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString(SessionKeyUserName)))
            {
                if (User.CheckCredentials(User.UserName, User.Password) == true)
                {
                    HttpContext.Session.SetString(SessionKeyUserName, User.UserName);
                }
                else
                {
                    return RedirectToPage("/Error");
                }
            }
            var name = HttpContext.Session.GetString(SessionKeyUserName);
            return RedirectToPage("/Index", name);
        }
        return RedirectToPage("/Login");
    }
}

IBaiWebApp/Pages/OrderPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IBaiWebApp.Pages
{
    public class OrderPageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

IBaiWebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IBaiWebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

IBaiWebApp/Pages/ProductCreation.cshtml.cs
using Domain_Layer.Classes;
using IBaiWebApp.Models;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Domain_Layer.Enums;
using Domain_Layer.ClassManagers;
using DataLayer;
namespace IBaiWebApp.Pages
{
   

    public class ProductCreationModel : PageModel
    {
        public ProductCreationModel()
        {
            PageTitle = "Create Product Form";
        }

        public string PageTitle { get; private set; }
        [BindProperty] public new ProductModel NewProduct { get; set; }
        int storeId;
        public void OnGet(int storeID)
        {
            ViewData["StoreID"] = storeID;
            storeId = storeID;
        }
        public void OnPost()
        {
            ModelState.Remove("NewProduct.ProductID");
            ModelState.Remove("NewProduct.Store");

            IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                ProductManager usm = new(new ProductData());
                Product newProduct = new Product(0, NewProduct.Name, NewProduct.Description, NewProduct.Price, NewProduct.ShippingFee, NewProduct.PictureUrl, NewProduct.Categories, new Store(NewProduct.StoreId));
                usm.WriteProduct(newProduct);
                int storeId = newProduct.Store.StoreId;
                RedirectToPage("/Success",storeId);
            }
            
        }
    }
}

IBaiWebApp/Pages/ProductPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Domain_Layer.Classes;
using Domain_Layer.ClassManagers;
using DataLayer;
using IBaiWebApp.Models;

namespace IBaiWebApp.Pages
{
    public class ProductPageModel : PageModel
    {
   
        public Product product;
        public void OnGet(int productId)
        {
            ViewData["ID"] = productId;
        }
    }
}

IBaiWebApp/Pages/ProfilePage.cshtml.cs
using Domain_Layer.ClassManagers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DataLayer;
using Domain_Layer.Classes;
using Domain_Layer.Enums;

namespace IBaiWebApp.Pages
{
    public class ProfilePageModel : PageModel
    {
        [BindProperty] public IBaiWebApp.Models.StoreModel Store { get; set; }
        [BindProperty] public IBaiWebApp.Models.UserModel User { get; set; }
        string  newUserName = String.Empty; 
        UserManager usr = new(new UserData());

        //would like not use empty constructor here but couldn't figure out how to make it work without
        User selUser = new();
        public void OnGet(string? name)
        {
            newUserName = name;
            selUser= usr.GetUserByUserName(new User(0, newUserName));
        }
        public void OnPostSetUserLevel()
        {
            selUser = usr.GetUserByUserName(new User(0, User.UserName));
            usr.UpdateUser(new User(selUser.UserId, selUser.LastName, selUser.FirstName, selUser.Email, User.UserLevel, selUser.UserName, selUser.Password, selUser.Address, selUser.TelephoneNumber));
        }
        public void OnPostChangeEmail()
        {
            usr.UpdateUser(new User(selUser.UserId, selUser.LastName, selUser.FirstName, User.Email, selUser.UserLevel, selUser.UserName, selUser.Password, selUser.Address, selUser.TelephoneNumber));
        }
    }
}

IBaiWebApp/Pages/Registration.cshtml.cs
using Domain_Layer.Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using IBaiWebApp.Models;
using Domain_Layer.ClassManagers;
using DataLayer;

namespace IBaiWebApp.Pages;

public class RegisterModel : PageModel
{
    public RegisterModel()
    {
        PageTitle = "Register Form";
    }
    
    public string PageTitle { get; private set; }
    [BindProperty] public new UserModel User { get; set; }
    public void OnGet()
    {
    }
    public void OnPost()
    {
        IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
        if (ModelState.IsValid)
        {
            UserManager usm = new(new UserData());
            User newUser = new User(0, User.LastName, User.FirstName, User.Email, User.UserLevel, User.UserName, User.Password, User.Address, User.TelephoneNumber);
            usm.WriteUser(newUser);
            RedirectToPage("/Index");
        }
    }
}

IBaiWebApp/Pages/StorePage.cshtml.cs
using Domain_Layer.Classes;
using Domain_Layer.ClassManagers;
using IBaiWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DataLayer;

namespace IBaiWebApp.Pages
{
    public class StorePageModel : PageModel
    {
        StoreManager storeManager = new(new StoreData());
        UserManager userManager = new(new UserData());
        [BindProperty] public StoreModel SelectedStore { get; set; }
        StoreModel selStore = new();

        public void OnGet(int storeId)
        {
            ViewData["StoreId"] = storeId;
        }
    }
}

IBaiWebApp/Pages/Success.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IBaiWebApp.Pages
{
    public class SuccessModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

IBaiWebApp/Pages/CreateStore.cshtml
@page
@using Domain_Layer.Classes;
@using Domain_Layer.ClassManagers;
@using Domain_Layer.Enums;
@using DataLayer;
@model CreateStoreModel

@{
	StoreManager storeManager = new(new StoreData());
	UserManager userManager = new(new UserData());
	string userName = HttpContext.Session.GetString("_UserName");
	List<User> userList = new();
	User user = userManager.GetUserByUserName(new User(0,userName));
	string[] catNames = Enum.GetNames(typeof(Categories));
}

@if (userName != null)
{
	Layout = "_LayoutLoggedIn";
}
else
{
	Layout = "_Layout";
}

@if (userName != null)
{
	@if (user.UserLevel == (int)UserLevels.SELLER || user.UserLevel == (int)UserLevels.PREMIUMSELLER || user.UserLevel == (int)UserLevels.ADMIN)
	{
		<div class="storeCreationBox"> 
			<form method="post">
				<label asp-for="NewStore.StoreName">Name:*</label>
				<span asp-validation-for="NewStore.StoreName"></span>
				<input asp-for="NewStore.StoreName" /><br />
				<label asp-for="NewStore.Description">Description:*</label>
				<span asp-validation-for="NewStore.Description"></span>
				<input asp-for="NewStore.Description" /><br />
				<select asp-for="NewStore.Categories">
					@for (int i = 0; i < catNames.Count(); i++)
					{
						<option value="@catNames[i].TrimEnd(',')">@catNames[i]</option>
					}
					</select>
					<span asp-validation-for="NewStore.Categories"></span>
					<span asp-validation-for="NewStore.Owner">@user.UserId</span>
					<div class="logReg_button_container">
					<input type="submit" value="Submit"/>
				</div>
			</form>
		</div>
	}
	else
	{
		<div class="storeCreationBox">
			<p> Become a seller! Go to your profile and change your user level:</p>
			<a href="/ProfilePage?name=@userName">Create your store</a>
		</div>

	}
}
else{
	RedirectToPage("/Registration");
}

IBaiWebApp/Pages/Index.cshtml
@page
@using Domain_Layer.Classes
@using Domain_Layer.ClassManagers
@using Domain_Layer.Enums
@using DataLayer
@model IndexModel
@{
    ProductManager dataCatalogue = new ProductManager(new ProductData());
    List<Product> prList = new List<Product>();
    try
    {
       prList = dataCatalogue.GetProducts();
    }
    catch (ArgumentOutOfRangeException) { }
}
@if (HttpContext.Session.GetString("_UserName") != null)
{
    Layout = "_LayoutLoggedIn";
}
else
{
    Layout = "_Layout";
}
@{
    //loops too many times, couldn't find a way to display properly.
    <div class="modularItemBox">
        @for (int i = 0; i < prList.Count(); i++)
        {
            var x = prList[i];
                <div class="test">
                    @for(int z = 0;z<prList.Count()/4;z++ ){
                        <div class="ItemRow + @z">
                            <div class="itemSquare">
                                    <div class="namePricePicSection">
                                        <div class="picSquare"><img class="itemPic" src="@x.PictureUrl" /></div>
                                        @x.Name<br>
                                        @x.Price$
                                    </div><br>
                                    <div class="descriptionSection">@x.Description<br></div>
                            <a asp-page="/ProductPage" asp-route-productID="@x.ProductID">Show Details</a>
                            </div>
                        </div>
                }
                </div>
        }
    </div>
}

IBaiWebApp/Pages/Login.cshtml
@page
@model LoginModel
@{
	ViewData["Title"] = "Login Page";
}
<div class="baseContainer">
	<div class="loginSquare">
		<form method="post">
			<label asp-for="User.UserName">Name:*</label>
			<span asp-validation-for="User.UserName"></span>
			<input asp-for="User.UserName"/><br/>
			<label asp-for="User.Password">Password:*</label>
			<span asp-validation-for="User.Password"></span>
			<input asp-for="User.Password"/><br/>
			<div class="button_container">
				<input type="submit" value="Submit"/>
			</div>
		</form>
	</div>
</div>

IBaiWebApp/Pages/OrderPage.cshtml
@page
@model IBaiWebApp.Pages.OrderPageModel
@{
}

IBaiWebApp/Pages/ProductCreation.cshtml
@page
@model IBaiWebApp.Pages.ProductCreationModel
@using Domain_Layer.Enums;
@using Domain_Layer.Classes;
@{
	int? storeId = Convert.ToInt32(ViewData["StoreId"]);
}
<div class="baseContainer">
	<div class="registerSquare">
		<form method="post">

			<label asp-for="NewProduct.Name">Name:*</label>
			<span asp-validation-for="NewProduct.Name"></span>
			<input asp-for="NewProduct.Name" /><br />

			<label asp-for="NewProduct.Description">Description:*</label>
			<span asp-validation-for="NewProduct.Description"></span>
			<input asp-for="NewProduct.Description" /><br />

			<label asp-for="NewProduct.Price">Price:*</label>
			<span asp-validation-for="NewProduct.Price"></span>
			<input asp-for="NewProduct.Price" /><br />

			<label asp-for="NewProduct.ShippingFee">ShippingFee:*</label>
			<span asp-validation-for="NewProduct.ShippingFee"></span>
			<input asp-for="NewProduct.ShippingFee" /><br />

			<label asp-for="NewProduct.PictureUrl">PictureUrl:*</label>
			<span asp-validation-for="NewProduct.PictureUrl"></span>
			<input asp-for="NewProduct.PictureUrl" /><br />
			<label asp-for="NewProduct.StoreId" readonly>StoreId:*</label>
			<span asp-validation-for="NewProduct.StoreId" readonly></span>
			<input asp-for="NewProduct.StoreId" value="@storeId" readonly /><br />
			


			<select asp-for="NewProduct.Categories" asp-items="Html.GetEnumSelectList<Categories>()">
				<option value="">Choose a category</option>
			</select>
			<div class="logReg_button_container">
				<input type="submit" value="Submit" />

			</div>

		</form>
	</div>
</div>

IBaiWebApp/Pages/ProductPage.cshtml
@page
@model IBaiWebApp.Pages.ProductPageModel
@using Domain_Layer.ClassManagers;
@using DataLayer;
@using Domain_Layer.Classes;
@{
	int productId = (int)ViewData["ID"];
	ProductManager productManager = new ProductManager(new ProductData());
	Product x = productManager.GetProduct(new Product(productId));
	string userName = HttpContext.Session.GetString("_UserName");
}
@if (userName != null)
{
	Layout = "_LayoutLoggedIn";
}
else
{
	Layout = "_Layout";
}
<div>
	@x.Name
	@x.Price
	@x.PictureUrl
	@x.Description;
</div>

IBaiWebApp/Pages/ProfilePage.cshtml
@page
@model IBaiWebApp.Pages.ProfilePageModel
@using Domain_Layer;
@using Domain_Layer.Classes;
@using Domain_Layer.ClassManagers;
@using DataLayer;
@using Domain_Layer.Enums;
@{
	StoreManager storeManager = new(new StoreData());
	UserManager userManager = new(new UserData());
	var userName = HttpContext.Session.GetString("_UserName");
	List<User> userList = new();
	User user = userManager.GetUserByUserName(new User(0, userName));
	string[] userLevels = Enum.GetNames(typeof(UserLevels));
}
@if (userName != null)
{
	Layout = "_LayoutLoggedIn";
}
else
{
	Layout = "_Layout";
}
<div class="baseContainer">
	Welcome @user.UserName, you can edit add or remove your infos here.<br />
	Change your User Level:
	<form class="form" method="post" asp-page-handler="SetUserLevel">
		<a as
	<select asp-for="User.UserLevel" >
		@for (int i = 0; i < userLevels.Count(); i++)
		{
			<option value="@userLevels[i]">@userLevels[i]</option>
		}
	</select>
		<input type="text" id="userName" name="name" />

		<div class="logReg_button_container">
			<input type="submit" value="Submit" />
		</div>
	</form>

	
</div>

IBaiWebApp/Pages/Registration.cshtml
@page
@model RegisterModel
@using Domain_Layer.Classes;
@using Domain_Layer.Enums;
@{
	ViewData["Title"] = "Register Page";
}
<div class="baseContainer">
	<div class="registerSquare">
		<form method="post">

			<label asp-for="User.FirstName">Name:*</label>
			<span asp-validation-for="User.FirstName"></span>
			<input asp-for="User.FirstName" /><br />

			<label asp-for="User.Password">Password:*</label>
			<span asp-validation-for="User.Password"></span>
			<input asp-for="User.Password" /><br />

			<label asp-for="User.LastName">LastName:*</label>
			<span asp-validation-for="User.LastName"></span>
			<input asp-for="User.LastName" /><br />

			<label asp-for="User.Email">Email:*</label>
			<span asp-validation-for="User.Email"></span>
			<input asp-for="User.Email" /><br />

			<label asp-for="User.UserName">UserName:*</label>
			<span asp-validation-for="User.UserName"></span>
			<input asp-for="User.UserName" /><br />

			<label asp-for="User.Address">Address:*</label>
			<span asp-validation-for="User.Address"></span>
			<input asp-for="User.Address" /><br />

			<label asp-for="User.TelephoneNumber">TelephoneNumber:*</label>
			<span asp-validation-for="User.TelephoneNumber"></span>
			<input asp-for="User.TelephoneNumber" /><br />

			<select asp-for="User.UserLevel" asp-items="Html.GetEnumSelectList<UserLevels>()">
				<option value="">Choose a Kind of user</option>
			</select>
			<div class="logReg_button_container">
				<input type="submit" value="Submit" />

			</div>

		</form>
	</div>
</div>

IBaiWebApp/Pages/StorePage.cshtml
@page
@using Domain_Layer.Classes
@using Domain_Layer.ClassManagers
@using Domain_Layer.Enums
@using DataLayer
@model IBaiWebApp.Pages.StorePageModel
@{
    ProductManager productCatalogue = new ProductManager(new ProductData());
    StoreManager storeManager = new StoreManager(new StoreData());
    List<Product> prList = new List<Product>();
    Store thisStore = storeManager.GetStores().Find(x => x.StoreId == (int)ViewData["StoreId"]);
    try
    {
        prList = productCatalogue.GetProducts().FindAll(x=>x.Store.StoreId == (int)ViewData["StoreId"]);
    }
    catch (Exception ex) { }
  
}
@if (HttpContext.Session.GetString("_UserName") != null)
{
    Layout = "_LayoutLoggedIn";
}
else
{
    Layout = "_Layout";
}
@if (thisStore.Owner.UserName == HttpContext.Session.GetString("_UserName"))
{
    <div>
        <a asp-page="/ProductCreation" asp-route-storeID="@thisStore.StoreId">Show Details</a>

    </div>
}

    <div class="modularItemBox">
        @for (int i = 0; i < prList.Count(); i++)
        {
            var x = prList[i];
                <div class="test">
                    @for(int z = 0;z<prList.Count()/4;z++ ){
                        <div class="ItemRow + @z">
                            <div class="itemSquare">
                                    <div class="namePricePicSection">
                                        <div class="picSquare"><img class="itemPic" src="@x.PictureUrl" /></div>
                                        @x.Name<br>
                                        @x.Price$
                                    </div><br>
                                    <div class="descriptionSection">@x.Description<br></div>
                                <button type ="button">Add to Cart</button>
                            </div>
                        </div>
                }
                </div>
        }
    </div>
}

IBaiWebApp/Pages/Success.cshtml
@page
@model IBaiWebApp.Pages.SuccessModel
@{
}